"""Generate a concrete component task from the manager's inspected inventory."""
import json
from backend.paths import VERSION, SafetyError
from backend.desktop import desktop_directory
from backend.store import DEFAULT_REPOSITORY

READ_FIRST = ["PROJECT_CONTEXT.md", "README.md", "docs/ARCHITECTURE.md", "docs/PLUGIN_SPEC.md",
              "docs/COMPONENT_SPEC.md", "docs/CODEX_PACKAGE_FORMAT.md", "docs/CODEX_WORKFLOW.md",
              "docs/COMPONENT_STORE.md", "docs/QUICK_TOGGLES_INTEGRATION.md", "docs/ANIMATED_TIMER_INTEGRATION.md", "docs/DASHBOARD_INTEGRATION.md",
              "docs/MANIFEST_VERSIONING.md", "docs/ADAPTER_API.md", "docs/PACKAGE_ARCHIVES.md", "docs/RECOVERY_MODEL.md"]

GIT_DELIVERY = """REQUIRED GIT DELIVERY
Always commit and push the completed changes to Git. This is part of every code task generated by this prompt, unless the current request explicitly says otherwise. Do not finish after only editing files or creating a local commit.
Before editing, inspect the repository root, branch, remotes, upstream, git status and existing differences. Preserve unrelated user work. Stage explicit task-owned paths or hunks; never use git add . or git add -A on a dirty checkout. Review the staged diff for secrets, unrelated changes and generated files before committing.
Use the correct existing remote and branch with the user's existing credentials. If this local manager project has no remote, locate or create a separate checkout of the suite publishing target below and transfer only reviewed task changes into its proper directories. Do not invent a remote, change global Git configuration, overwrite unrelated files or force-push. Do not commit environments, credentials, runtime state, logs, backups, caches, build output or reference clones.
Push the scoped commit and verify the exact resulting remote branch/commit with a fresh Git read. A successful local commit is not proof of a push. If authentication, branch protection, missing repository information or a failed push prevents delivery, report the concrete blocker and retain the completed changes; never claim that they were pushed.
Component Store publication additionally requires components/<id>/ on main. A pushed feature branch or PR is pending until merged into main. After publication, use a fresh Store.scan() with an isolated cache and verify the component ID, version and source_hash. Report the remote link, branch and commit, relevant test results and any remaining blocker. Git delivery never authorizes installing, enabling or restarting a live component."""

IMPLEMENTATION = """IMPLEMENTATION CONTRACT
Make the requested behavior work in the real component runtime. Components live under plugins/<component-id>/ and must not require Dev Manager to remain open. Do not create component runtime pages inside the manager. Manager UI/backend changes belong to the manager itself.
Inspect installed Caelestia source before using dashboard, panel, plugin or window APIs. Do not invent extension points. Preserve Cast Audio, TouchDeck, Animated Timer and unrelated integrations. The verified manager-owned host adapters are:
- cast-audio: caelestia-plugin / quickshell / integration.target=caelestia-quick-toggles. Read docs/QUICK_TOGGLES_INTEGRATION.md.
- animated-timer: caelestia-plugin / quickshell / integration.target=caelestia-dashboard-timer. Read docs/ANIMATED_TIMER_INTEGRATION.md. The adapter pins Caelestia KDE v2.5.1 and the verified commit/host checksums.
Future dashboard components declare integration.target=caelestia-dashboard and the strict dashboard page descriptor in docs/DASHBOARD_INTEGRATION.md (manager 0.7.0+). Reuse the shared adapter rather than copying Timer or adding component-ID branches. These are manager-owned bridges, not upstream registration APIs. Reviewed lifecycle actions preserve originals, display exact host changes, reject unexpected modifications and support recovery/uninstall. New installs enable these integrations and reload the shell; updates preserve enabled state. Other plugins require their supported explicit activation/reload workflow.
Prepare source and an exact, reviewable lifecycle plan before changing installed code. Do not install or restart the production shell as a development test. Run automated lifecycle tests in temporary XDG directories; preserve real user configuration, receipts, backups and unrelated edits.
Use complete UTF-8 source, local SVG artwork, semantic versions, safe relative paths and lowercase hyphenated IDs. New manifests use schema_version=2; older schemas remain readable without rewriting source. Declare binary resources with their exact MIME and SHA-256 and transfer them through folder import or .cdmpkg, not text paste packages. Give every component a distinct assets/icon.svg and declare desktop.icon=assets/icon.svg, including shell plugins (the icon does not create a desktop shortcut). Do not depend on a desktop theme's generic icon. Keep manifest.json and Caelestia metadata.json identity/version/entrypoint fields synchronized. Include imported modules, assets, README, dependencies, permissions, tests and rollback instructions. Do not deliver placeholders or partial files.
No arbitrary installer hooks, sudo, broad deletion, unsafe symlinks, traversal, global pip changes or component-supplied host patches. Static validation must not execute component source. Reserved KDE integration and unknown integration targets remain unsupported.
Standalone apps and scripts may optionally set desktop.createShortcut=true (default false). Use the manager's reviewed canonical launcher and configured XDG desktop directory, never hardcode ~/Desktop. Services and shell integrations cannot request desktop shortcuts.

DEPENDENCY AND VERIFICATION WORKFLOW
Use the inventory's exact validation errors, installed/source differences and dependency reports to diagnose failures. Missing executable errors are real blockers: keep required dependencies and fix their setup, rather than weakening validation. System dependencies are executable names; Python dependencies are distribution requirements for the private component environment.
The manager prepares Python dependencies for Python/PySide6 components and Quickshell sidecars. A sidecar with Python dependencies must use installed _venv/bin/python and invoke tools as modules to avoid staging shebangs. Cast Audio uses catt==0.13.3 and a fixed reviewed package/firewall recipe. Other system tools need explicit setup. Preserve source-review and restart warnings. Select addresses from the route to a receiver; never hardcode development machine IPs or invent Google-account discovery APIs.
Run checks appropriate to the actual change. Exercise interaction, persistence, cancellation and rapid input where relevant, and regression-check affected integrations. Distinguish automated coverage from hardware/audio/monitor checks you actually performed. Validate the exact publishable mapping with backend.store.checked_files and backend.validators.validate; machine-specific compatibility and dependency readiness still matter.

DELIVERY CHECKLIST
1. Complete and verify the requested behavior; resolve discovered failures within scope.
2. Prepare the store-ready components/<id>/ tree for a component build/update. Manager changes belong under caelestia-dev-manager/ in the suite. Bump versions for released updates and include all referenced files.
3. Review the scoped diff, commit and push as required below; verify the remote result. Report any concrete delivery blocker.
4. Give a concise result with changed files, tests, compatibility limits, remote commit and any reviewed installation step still pending.
If the user will paste your answer into Dev Manager, output one complete CAELESTIA_DEV_PACKAGE with exact --- FILE: path --- sections; use the attached package contract. Local plugins/ source alone is not a published Store entry."""


def context(manager, request, statuses=None, dependencies=None):
    components = [{"id": r["id"], "name": r["manifest"]["name"], "type": r["manifest"]["type"],
                   "version": r["manifest"]["version"], "runtime": r["manifest"]["runtime"],
                   "entrypoint": r["manifest"].get("entrypoint"),
                   "icon": r["manifest"].get("desktop", {}).get("icon"),
                   "integration": r["manifest"].get("integration", {}),
                   "dependencies": r["manifest"].get("dependencies", {}),
                   "validation": r.get("validation", {}),
                   "dependency_report": (dependencies or {}).get(r["id"]),
                   "source_hash": r.get("source_hash"), "store_origin": r.get("store_origin"),
                   "installed_version": r.get("installed_manifest", {}).get("version"),
                   "installed": r.get("installed", False), "enabled": r.get("enabled", False),
                   "status": r["status"], "source": str(manager.paths.source(r["id"])),
                   "desktop_shortcut_created": r["desktop_shortcut_created"],
                   "desktop_shortcut_path": (r.get("desktop_shortcut") or {}).get("path")}
                  for r in (manager.all_status() if statuses is None else statuses)]
    try:
        directory = desktop_directory(manager.paths)
        desktop_path = str(directory) if directory else None
    except SafetyError as error:
        desktop_path = "Unavailable: " + str(error)
    parts = [f"You are working with Caelestia Dev Manager {VERSION}. Complete the current request end to end.",
             "CURRENT REQUEST:\n" + (request.strip() or "No task entered yet. Ask for the concrete change before modifying files."),
             "Before writing code read:\n" + "\n".join(READ_FIRST),
             "Project directory: " + str(manager.paths.project),
             GIT_DELIVERY,
             "Environment (latest read-only inspection snapshot; refresh if it has changed):\n" + json.dumps(manager.environment, indent=2),
             "Existing components:\n" + json.dumps(components, indent=2),
             "Component Store publishing target:\n" + json.dumps({"repository": DEFAULT_REPOSITORY, "branch": "main",
                 "manager_directory": "caelestia-dev-manager/", "published_components": "components/<component-id>/",
                 "local_development_source": str(manager.paths.sources)}, indent=2),
             "Paths:\n" + json.dumps({"source": str(manager.paths.sources), "apps": str(manager.paths.manager / "apps"),
                 "commands": str(manager.paths.bin), "desktop_entries": str(manager.paths.data / "applications"),
                 "desktop_shortcuts": desktop_path, "services": str(manager.paths.config / "systemd/user"),
                 "plugins": str(manager.paths.config / "caelestia/plugins")}, indent=2),
             IMPLEMENTATION]
    for doc in ("docs/ARCHITECTURE.md", "docs/COMPONENT_SPEC.md", "docs/CODEX_PACKAGE_FORMAT.md", "docs/CODEX_WORKFLOW.md",
                "docs/COMPONENT_STORE.md", "docs/QUICK_TOGGLES_INTEGRATION.md", "docs/ANIMATED_TIMER_INTEGRATION.md", "docs/DASHBOARD_INTEGRATION.md"):
        path = manager.paths.project / doc
        if path.exists():
            parts.append(f"--- {doc} ---\n" + path.read_text())
    return "\n\n".join(parts)
